### PR TITLE
Formatting and 0.12 syntax (No Functionality Changes)

### PR DESCRIPTION
**Pull request by rraub**
Looks like there were some places that were not auto formatted and the old hcl language syntax is used. 

This PR updates just formatting, there should be 0 functional changes.  Sorry to be the one to issue a 353 line PR thats just formatting 😬

### CODE REVIEW

**Comment by rraub** [comment]
@mobileoverlord if you have a minute could you take a look at this PR?

**Comment by mobileoverlord** [comment]
lol, thats a lot of lines. Thanks for this though. I was recently informed of the issues with the usage of terraform 0.12. I'll run this locally and take a peek. thanks!!!!!

**Comment by rraub** [comment]
> lol, thats a lot of lines. Thanks for this though. I was recently informed of the issues with the usage of terraform 0.12. I'll run this locally and take a peek. thanks!!!!!

This repository was already setup to use Terraform v0.12  https://github.com/nerves-hub/terraform/blob/dba0a8e3d6bf0e23d9ceb5dbe80f8974e05d922a/base/versions.tf#L3

v0.12 does supports the older syntax (its just deprecated) and there are spots in this repo where that new syntax was already used, https://github.com/nerves-hub/terraform/blob/master/setup/setup.tf#L18-L22 

This PR just fixes the remaining places and updates the formatting to the `terraform fmt` spec


If you run a terraform plan on the master branch and then switch to this branch you should see the same plan output.

**Comment by rraub** [comment]
@mobileoverlord Just checking in if you've had a chance to look at these PRs. Let me know if I can do anything to help make the test and review easier for you!  Thanks!

**Comment by mobileoverlord** [comment]
I've been trying to get back around to testing this out but now that my machine has updated to terraform 0.13 and my `-backend-config=path/to/staging.tfvars' is not being read in correctly when I am trying to initialize the backend.

```
Error: Unsupported argument

  on staging.tfvars line 12:
  12: domain = "nerves-hub.org"

An argument named "domain" is not expected here.
```

The path I am trying to execute it in has a `variables.tf` file with all the declared values. 

Apparently this is a "feature" of terraform 0.13 and now its unclear what the "correct" workflow is since terraform docs seem to be of the 0.12 era.

**Comment by rraub** [comment]
[Terraform 0.13.x does introduce breaking changes](https://www.terraform.io/upgrade-guides/0-13.html) and this repo isn't quite compatible with it yet. We use [asdf](https://github.com/asdf-vm/asdf) to control the version of terraform for our repositories so that way we don't run into surprise upgrades. It's not hard to setup and just takes a single file in a directory to set the context for what versions of tools to use.

.tool-versions
```
terraform 0.12.29
```

**Pull request merged**
